---
- name: wait for graylog to configure
  uri:
    url: "http://{{ graylog_address }}"
    status_code: 200,403
    timeout: 5
  register: graylog_service_status
  retries: 15
  delay: 5
  until:
    - ('status' in graylog_service_status)
    - (graylog_service_status['status'] == 200) or (graylog_service_status['status'] == 403)

- name: get index id
  uri:
    url: "http://{{ graylog_address }}/api/system/indices/index_sets"
    user: "{{ graylog_root.username }}"
    password: "{{ graylog_root.password }}"
    method: GET
    return_content: yes
  register: response
  retries: 10
  delay: 5
  until:
    - (response['status'] == 200) or (response['status'] == 403)

- name: configure index retention
  uri:
    url: "http://{{ graylog_address }}/api/system/indices/index_sets/{{ response.json.index_sets[0].id }}"
    user: "{{ graylog_root.username }}"
    password: "{{ graylog_root.password }}"
    method: PUT
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{{ graylog_logretention_conf }}"

- name: configure inputs
  uri:
    url: "http://{{ graylog_address }}/api/system/inputs"
    user: "{{ graylog_root.username }}"
    password: "{{ graylog_root.password }}"
    method: POST
    force_basic_auth: yes
    status_code: 201
    body_format: json
    body: "{{ item }}"
  with_items: "{{ graylog_input_conf }}"
