
---
- name: Directory should be created with correct ownership and privileges
  file:
    path: '/etc/graylog/server'
    owner: graylog
    group: graylog
    mode: '0750'

- name: Fail when salt is not specified
  fail:
    msg: "Run 'pwgen -N 1 -s 96' for random salt"
  when: graylog_password_salt == ""

- name: Graylog server should be configured
  template:
    src: 'graylog.server.conf.j2'
    dest: '/etc/graylog/server/server.conf'
    owner: graylog
    group: graylog
    mode: 0644
  notify: restart graylog

#- name: Graylog server defaults should be configured
#  template:
#    src: 'graylog.server.default.j2'
#    dest: '/etc/default/graylog-server'
#    owner: graylog
#    group: graylog
#    mode: '0644'
#  when: ansible_os_family == 'Debian'
#  notify: restart graylog
#
#- name: Configure Graylog server sysconfig
#  template:
#    src: graylog.server.default.j2
#    dest: '/etc/sysconfig/graylog-server'
#    owner: graylog
#    group: graylog
#    mode: '0644'
#  when: ansible_os_family == 'RedHat'
#  notify: restart graylog

- name: Graylog server should start after reboot
  file:
    path: '/etc/init/graylog-server.override'
    state: absent

#- name: Create mongodb user
